import React, { useEffect, useState } from "react";
import useAuthStore from "../store/authStore";
import useApplicationStore from "../store/applicationStore";
import useJobStore from "../store/jobStore";
import { useNavigate } from "react-router-dom";
import { motion, AnimatePresence } from "framer-motion";
import {
  ExternalLink,
  Clock,
  Building2,
  CheckCircle2,
  XCircle,
  Loader2,
  Sparkles,
  Rocket,
  Compass,
  Eye,
  Image as ImageIcon,
  TrendingUp,
  Zap,
  Target,
} from "lucide-react";
// Lazy load 3D components
const CareerOrb = React.lazy(() => import("../three-ui/CareerOrb"));
const FloatingShapes = React.lazy(() => import("../three-ui/FloatingShapes"));
const StatOrb = React.lazy(() => import("../three-ui/StatOrb"));

const ProofModal = ({ application, onClose }) => {
  if (!application) return null;
  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm"
      onClick={onClose}
    >
      <motion.div
        initial={{ scale: 0.9, y: 20 }}
        animate={{ scale: 1, y: 0 }}
        className="glass max-w-5xl w-full max-h-[90vh] overflow-hidden rounded-3xl flex flex-col"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="p-6 border-b border-white/10 flex justify-between items-center bg-white/5">
          <div>
            <h3 className="text-xl font-bold">{application.jobId?.title}</h3>
            <p className="text-sm text-gray-400">
              {application.jobId?.company} • Visual Proof
            </p>
          </div>
          <button
            onClick={onClose}
            className="p-2 hover:bg-white/10 rounded-full transition-all"
          >
            <XCircle className="h-6 w-6" />
          </button>
        </div>
        <div className="flex-1 overflow-y-auto p-4 bg-black/40">
          {application.screenshot ? (
            <img
              src={`http://localhost:5000${application.screenshot}`}
              alt="Application Proof"
              className="w-full h-auto rounded-xl border border-white/10 shadow-2xl"
            />
          ) : (
            <div className="h-64 flex flex-col items-center justify-center text-gray-500 italic">
              <ImageIcon className="h-12 w-12 mb-4 opacity-20" />
              <p>Visual proof is being generated by the automation engine...</p>
            </div>
          )}

          <div className="mt-6 p-6 bg-white/5 rounded-2xl border border-white/5">
            <h4 className="text-primary font-bold mb-2 flex items-center gap-2">
              <Sparkles className="h-4 w-4" /> AI Personalization Summary
            </h4>
            <p className="text-gray-400 text-sm leading-relaxed">
              {application.notes ||
                "Automation engine is currently processing this board with AI-driven answers to custom questions."}
            </p>
          </div>
        </div>
      </motion.div>
    </motion.div>
  );
};

const glassClass =
  "bg-white/5 backdrop-blur-xl border border-white/10 shadow-2xl";
const glassCardClass = `${glassClass} rounded-3xl transition-all duration-500 border-white/5 hover:bg-white/10 hover:border-white/20`;
const btnPrimaryClass =
  "bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-500 hover:to-purple-500 text-white font-bold py-3 px-6 rounded-2xl transition-all duration-300 shadow-lg shadow-indigo-500/20 active:scale-[0.98]";

const StatCard = React.memo(({ stat, index }) => (
  <motion.div
    initial={{ opacity: 0, y: 30 }}
    animate={{ opacity: 1, y: 0 }}
    transition={{ delay: index * 0.1, duration: 0.8, ease: "easeOut" }}
    whileHover={{ scale: 1.02, y: -5 }}
    className={`${glassCardClass} p-6 flex flex-col justify-between relative overflow-hidden cursor-pointer group`}
  >
    <div className="absolute -right-8 -top-8 opacity-30 group-hover:opacity-50 transition-opacity">
      <React.Suspense
        fallback={<div className="h-10 w-10 bg-white/5 rounded-full" />}
      >
        <StatOrb value={stat.value} color={stat.color} />
      </React.Suspense>
    </div>
    <div className="relative z-10">
      <div className="flex items-center gap-2 mb-4">
        <div className={`p-2 rounded-xl bg-white/5 ${stat.iconColor}`}>
          <stat.icon className="h-4 w-4" />
        </div>
        <h3 className="text-slate-500 text-[10px] font-bold uppercase tracking-[0.2em]">
          {stat.label}
        </h3>
      </div>
      <p
        className={`text-5xl font-black font-display tracking-tight ${stat.iconColor}`}
      >
        {stat.value}
      </p>
    </div>
    <div className="absolute bottom-0 left-0 right-0 h-1 bg-gradient-to-r from-transparent via-white/10 to-transparent" />
  </motion.div>
));

const ApplicationsTable = React.memo(({ applications, onSelectProof }) => (
  <div className="overflow-x-auto">
    <table className="w-full text-left border-collapse">
      <thead>
        <tr className="text-slate-500 text-[10px] font-bold uppercase tracking-[0.2em] border-b border-white/5">
          <th className="px-8 py-6">Job Role</th>
          <th className="px-8 py-6">Company</th>
          <th className="px-8 py-6">Status</th>
          <th className="px-8 py-6">Proof</th>
          <th className="px-8 py-6 text-right">Reference</th>
        </tr>
      </thead>
      <tbody className="divide-y divide-white/[0.03]">
        {applications.length === 0 ? (
          <tr>
            <td
              colSpan="5"
              className="px-8 py-20 text-center text-slate-500 italic font-medium"
            >
              The discovery engine is currently scanning for your first role...
            </td>
          </tr>
        ) : (
          applications.map((app) => (
            <tr
              key={app._id}
              className="hover:bg-white/[0.03] transition-all duration-300 group"
            >
              <td className="px-8 py-6">
                <div className="font-bold text-slate-200 group-hover:text-indigo-400 transition-colors">
                  {app.jobId?.title || "Unknown Role"}
                </div>
              </td>
              <td className="px-8 py-6">
                <div className="flex items-center gap-3">
                  <div className="h-8 w-8 rounded-lg bg-white/5 flex items-center justify-center text-xs font-bold border border-white/10 group-hover:border-white/20 transition-all">
                    {app.jobId?.company?.[0] || "?"}
                  </div>
                  <span className="text-slate-400 font-medium">
                    {app.jobId?.company || "Unknown"}
                  </span>
                </div>
              </td>
              <td className="px-8 py-6">
                <span
                  className={`inline-flex items-center gap-2 px-4 py-1.5 rounded-full text-[10px] font-bold uppercase tracking-widest border transition-all ${
                    app.status === "Applied"
                      ? "bg-emerald-500/10 text-emerald-400 border-emerald-500/20 shadow-[0_0_10px_rgba(16,185,129,0.1)]"
                      : app.status === "Failed"
                        ? "bg-rose-500/10 text-rose-400 border-rose-500/20"
                        : "bg-indigo-500/10 text-indigo-400 border-indigo-500/20"
                  }`}
                >
                  {app.status === "Pending" && (
                    <Loader2 className="h-3 w-3 animate-spin" />
                  )}
                  {app.status}
                </span>
              </td>
              <td className="px-8 py-6">
                <button
                  onClick={() => onSelectProof(app)}
                  className={`p-2.5 rounded-xl transition-all duration-300 ${
                    app.screenshot
                      ? "bg-indigo-500/20 text-indigo-400 hover:bg-indigo-500/30 hover:scale-110 active:scale-95"
                      : "bg-white/5 text-slate-600 cursor-not-allowed opacity-40"
                  }`}
                  disabled={!app.screenshot}
                >
                  <Eye className="h-5 w-5" />
                </button>
              </td>
              <td className="px-8 py-6 text-right">
                <a
                  href={app.jobId?.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex p-2.5 text-slate-500 hover:text-white hover:bg-white/10 rounded-xl transition-all"
                >
                  <ExternalLink className="h-5 w-5" />
                </a>
              </td>
            </tr>
          ))
        )}
      </tbody>
    </table>
  </div>
));

const Dashboard = () => {
  const user = useAuthStore((state) => state.user);
  const logout = useAuthStore((state) => state.logout);
  const { applications, fetchApplications, loading, massApply } =
    useApplicationStore();
  const { jobs, fetchJobs } = useJobStore();
  const navigate = useNavigate();
  const [massApplying, setMassApplying] = useState(false);
  const [selectedProof, setSelectedProof] = useState(null);

  useEffect(() => {
    fetchApplications();
    fetchJobs({ experienceLevel: "Entry" });
    const interval = setInterval(
      () => fetchApplications({ background: true }),
      10000,
    );
    return () => clearInterval(interval);
  }, []);

  const fresherJobs = React.useMemo(
    () => jobs.filter((j) => j.experienceLevel === "Entry"),
    [jobs],
  );
  const unappliedFresherJobs = React.useMemo(
    () =>
      fresherJobs.filter(
        (j) => !applications.some((a) => a.jobId?._id === j._id),
      ),
    [fresherJobs, applications],
  );

  const stats = React.useMemo(
    () => ({
      total: applications.length,
      applied: applications.filter((a) => a.status === "Applied").length,
      pending: applications.filter((a) => a.status === "Pending").length,
      failed: applications.filter((a) => a.status === "Failed").length,
    }),
    [applications],
  );

  return (
    <div className="min-h-screen bg-[#030712] text-slate-100 p-8 font-sans relative overflow-hidden">
      <React.Suspense
        fallback={<div className="absolute inset-0 bg-black/50" />}
      >
        <FloatingShapes />
      </React.Suspense>
      <div className="max-w-7xl mx-auto relative z-10">
        <header className="flex justify-between items-center mb-16">
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
          >
            <h1 className="text-5xl font-extrabold font-display text-gradient tracking-tight">
              Hello, {user?.name?.split(" ")[0] || "User"}
            </h1>
            <p className="text-slate-400 mt-2 font-medium">
              Your global automation desk is active.
            </p>
          </motion.div>
          <button
            onClick={() => {
              logout();
              navigate("/login");
            }}
            className="px-6 py-3 rounded-2xl bg-white/5 border border-white/10 hover:bg-white/10 transition-all text-sm font-semibold"
          >
            Sign Out
          </button>
        </header>

        <div className="grid grid-cols-1 lg:grid-cols-4 gap-8 mb-16">
          {/* 3D Visual Section */}
          <div
            className={`lg:col-span-1 ${glassCardClass} p-8 flex flex-col items-center justify-between relative overflow-hidden group`}
          >
            <div className="absolute top-6 left-8 z-10">
              <h3 className="text-slate-400 text-[10px] font-bold uppercase tracking-[0.2em] flex items-center gap-2">
                <div className="h-1.5 w-1.5 rounded-full bg-indigo-500 animate-pulse" />{" "}
                Growth Engine
              </h3>
            </div>
            <React.Suspense
              fallback={
                <div className="h-72 w-full flex items-center justify-center text-white/5">
                  <Loader2 className="animate-spin" />
                </div>
              }
            >
              <CareerOrb count={stats.applied} />
            </React.Suspense>
            <div className="text-center z-10 w-full">
              <div className="h-1.5 w-full bg-white/5 rounded-full overflow-hidden mb-3">
                <motion.div
                  initial={{ width: 0 }}
                  animate={{
                    width: `${Math.min((stats.applied / 10) * 100, 100)}%`,
                  }}
                  className="h-full bg-gradient-to-r from-indigo-500 to-purple-500 shadow-[0_0_15px_rgba(99,102,241,0.5)]"
                />
              </div>
              <p className="text-[10px] text-slate-500 font-bold uppercase tracking-widest">
                Efficiency: {Math.min(stats.applied * 10, 100)}%
              </p>
            </div>
          </div>

          <div className="lg:col-span-3 grid grid-cols-1 md:grid-cols-3 gap-6">
            {[
              {
                label: "Total Tracked",
                value: stats.total,
                color: "#ffffff",
                icon: TrendingUp,
                iconColor: "text-white",
              },
              {
                label: "Successfully Applied",
                value: stats.applied,
                color: "#34d399",
                icon: CheckCircle2,
                iconColor: "text-emerald-400",
              },
              {
                label: "Active Queue",
                value: stats.pending,
                color: "#818cf8",
                icon: Zap,
                iconColor: "text-indigo-400",
              },
            ].map((stat, i) => (
              <StatCard key={i} stat={stat} index={i} />
            ))}
          </div>
        </div>

        {/* Applications List */}
        <div className={`${glassCardClass} overflow-hidden border-none mb-16`}>
          <div className="p-8 border-b border-white/5 bg-white/[0.02] flex justify-between items-center">
            <h2 className="text-2xl font-bold font-display">Recent Activity</h2>
            <div className="flex gap-2">
              <div className="h-2 w-2 rounded-full bg-emerald-500 animate-pulse" />
              <span className="text-[10px] font-bold uppercase tracking-widest text-slate-500">
                Live Updates Enabled
              </span>
            </div>
          </div>

          <ApplicationsTable
            applications={applications}
            onSelectProof={setSelectedProof}
          />
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-20">
          <motion.div
            whileHover={{ y: -5 }}
            className={`${glassCardClass} p-10 border-indigo-500/30 bg-indigo-500/[0.03] flex flex-col justify-between`}
          >
            <div>
              <h2 className="text-3xl font-black mb-4 flex items-center gap-3 font-display tracking-tight">
                <Rocket className="h-8 w-8 text-indigo-400" /> Opportunities
              </h2>
              <p className="text-slate-400 mb-8 font-medium leading-relaxed">
                We've curated{" "}
                <span className="text-white font-bold">
                  {fresherJobs.length}
                </span>{" "}
                high-growth roles matching your global profile.
                <span className="text-indigo-400 block mt-1">
                  Discovery engine status: Highly Active.
                </span>
              </p>
            </div>
            <div className="flex gap-4">
              <button
                onClick={async () => {
                  setMassApplying(true);
                  const ids = unappliedFresherJobs
                    .slice(0, 50)
                    .map((j) => j._id);
                  if (ids.length > 0) await massApply(ids);
                  setMassApplying(false);
                }}
                disabled={massApplying || unappliedFresherJobs.length === 0}
                className={`flex-1 ${btnPrimaryClass} flex items-center justify-center gap-3 group`}
              >
                {massApplying ? (
                  <Loader2 className="h-5 w-5 animate-spin" />
                ) : (
                  <Sparkles className="h-5 w-5 group-hover:rotate-12 transition-transform" />
                )}
                Autoscale Apply ({Math.min(unappliedFresherJobs.length, 50)})
              </button>
              <button
                onClick={() => navigate("/discovery")}
                className="px-8 py-4 bg-white/5 border border-white/10 rounded-2xl font-bold hover:bg-white/10 transition-all active:scale-95"
              >
                Explore Hub
              </button>
            </div>
          </motion.div>

          <div className={`${glassCardClass} p-10 flex flex-col h-full`}>
            <h3 className="text-xl font-bold mb-8 flex items-center gap-3 font-display">
              <div className="h-2 w-2 rounded-full bg-purple-500" /> Real-time
              Feed
            </h3>
            <div className="space-y-4 overflow-y-auto pr-2 custom-scrollbar flex-1">
              {jobs.slice(0, 4).map((job, i) => (
                <div
                  key={i}
                  className="flex justify-between items-center p-5 bg-white/[0.02] rounded-2xl border border-white/5 hover:border-white/10 hover:bg-white/[0.04] transition-all group cursor-pointer"
                >
                  <div className="flex items-center gap-4">
                    <div className="h-10 w-10 rounded-xl bg-gradient-to-br from-indigo-500/10 to-purple-500/10 flex items-center justify-center text-indigo-400 font-bold border border-indigo-500/10">
                      {job.company?.[0]}
                    </div>
                    <div>
                      <h4 className="font-bold text-sm text-slate-200">
                        {job.title.length > 30
                          ? job.title.substring(0, 30) + "..."
                          : job.title}
                      </h4>
                      <p className="text-[10px] text-slate-500 font-bold uppercase tracking-widest">
                        {job.company}
                      </p>
                    </div>
                  </div>
                  <div className="p-2 bg-white/5 rounded-lg opacity-0 group-hover:opacity-100 transition-all text-slate-400">
                    <ExternalLink className="h-4 w-4" />
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      <AnimatePresence>
        {selectedProof && (
          <ProofModal
            application={selectedProof}
            onClose={() => setSelectedProof(null)}
          />
        )}
      </AnimatePresence>
    </div>
  );
};

export default Dashboard;
